notifications:
  email:
    on_success: never
    on_failure: always

language: android
name: "Build Bitmark Android SDK"
jdk: oraclejdk8
sudo: required
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.2
    - android-28
    - android-27
    - android-21
    - sys-img-armeabi-v7a-android-21
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - chmod +x gradlew
install:
before_script:
script:
  - ./gradlew clean build -p api-service --info
  - ./gradlew clean build -p cryptography --info
  - ./gradlew clean build -p java-sdk --info

branches:
  only:
    - devel
    - master
    - standardization
env:
  - ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle