notifications:
  email:
    on_success: never
    on_failure: always

language: android
name: "Build Bitmark Android SDK"
jdk: oraclejdk8
sudo: required
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.2
  - android-28
  - android-27
  - sys-img-armeabi-v7a-android-21
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
- chmod +x gradlew
- echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
install:
- echo y | sdkmanager "ndk-bundle"
- echo y | sdkmanager "cmake;3.6.4111459"
before_script:
- NDK_HOME=$ANDROID_NDK_HOME && SDK_HOME=$ANDROID_HOME && BINTRAY_USER=$BINTRAY_USER && BINTRAY_API_KEY=$BINTRAY_API_KEY && BINTRAY_GPG_PASS=$BINTRAY_GPG_PASS && BINTRAY_REPO=$BINTRAY_REPO
- mkdir -p local.properties && echo -n >local.properties && echo "ndk.dir=$NDK_HOME"$'\n'"sdk.dir=$SDK_HOME"$'\n'"bintray.user=$BINTRAY_USER"$'\n'"bintray.apikey=$BINTRAY_API_KEY"$'\n'"bintray.gpg.password=$BINTRAY_GPG_PASS"$'\n'"bintray.repo=$BINTRAY_REPO" >local.properties
script:
# Build & test
- ./gradlew clean test connectAndroidTest -p cryptography --info
- ./gradlew clean build -p api-service --info
- ./gradlew clean build -p java-sdk --info
- ./gradlew clean test connectAndroidTest -p android-sdk --info

# Deploy
#- ./.travis/deploy.sh

branches:
  only:
  - devel
  - master
  - standardization
env:
- ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle